In [1]:
%matplotlib inline 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.randn()

-0.7752396058121193

In [3]:
np.random.randn(5)

array([-0.03586553, -1.53812452,  0.48269932,  0.1822523 ,  1.32543817])

In [4]:
np.random.randn(2,4)

array([[-0.76636839, -0.6979135 ,  1.16669991, -1.66721536],
       [ 0.65513188,  0.97497775,  0.12130007,  0.48647873]])

In [5]:
np.random.randint(2,10,size=12)

array([6, 2, 6, 3, 7, 8, 4, 4, 3, 8, 6, 4])

In [6]:
np.random.randint(2,10,size=22)

array([3, 8, 9, 7, 2, 7, 3, 3, 6, 9, 5, 2, 5, 5, 5, 8, 3, 7, 6, 2, 5, 9])

In [19]:
np.random.randint(3)

2

In [26]:
k=np.array([1,2,3,4,5,6])

In [28]:
k.mean()

3.5