In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.random.randn(100)

In [5]:
A

array([-6.07981329e-01,  5.06788325e-02,  2.26640465e-01, -1.36278751e-01,
        1.72457716e+00, -3.31034898e-01, -1.79409284e+00,  5.28257295e-01,
       -2.90338751e-01, -7.27570282e-01,  9.96748604e-01,  1.94089322e-01,
        7.76232994e-01,  9.44647312e-01,  4.83919332e-01,  2.41689769e+00,
       -3.72473621e-01, -1.61176632e-01,  4.43376112e-01, -4.33833769e-01,
        7.90817054e-01,  1.58497859e+00,  7.60027401e-01, -1.42730570e+00,
       -7.12569631e-01,  5.43512898e-02, -4.11466221e-01, -8.19671415e-01,
       -4.53203550e-01,  2.55645074e-01, -8.42220424e-01,  1.17009473e+00,
        2.05905759e-01, -1.17627675e-01,  8.31510307e-01,  1.49828798e-01,
       -1.50781748e+00, -9.13922465e-01,  5.30718880e-01, -1.25482642e+00,
       -1.75204014e-01,  2.78228428e-01, -2.97679890e-01, -2.74968146e-01,
       -9.78558410e-02,  1.45284261e+00, -7.54687155e-01,  1.13225759e+00,
        9.51606002e-01, -9.96832001e-01, -1.17539411e+00, -8.93753105e-01,
        2.02442577e-01, -

In [6]:
A*10+50

array([43.92018671, 50.50678832, 52.26640465, 48.63721249, 67.2457716 ,
       46.68965102, 32.05907164, 55.28257295, 47.09661249, 42.72429718,
       59.96748604, 51.94089322, 57.76232994, 59.44647312, 54.83919332,
       74.16897693, 46.27526379, 48.38823368, 54.43376112, 45.66166231,
       57.90817054, 65.84978591, 57.60027401, 35.72694297, 42.87430369,
       50.5435129 , 45.88533779, 41.80328585, 45.4679645 , 52.55645074,
       41.57779576, 61.70094726, 52.05905759, 48.82372325, 58.31510307,
       51.49828798, 34.92182517, 40.86077535, 55.3071888 , 37.45173581,
       48.24795986, 52.78228428, 47.0232011 , 47.25031854, 49.02144159,
       64.52842614, 42.45312845, 61.32257593, 59.51606002, 40.03167999,
       38.24605894, 41.06246895, 52.02442577, 48.90906971, 44.84001422,
       50.75230426, 61.92110266, 73.74405664, 52.02989559, 47.65119299,
       49.84366673, 48.58266103, 32.57712868, 44.34053551, 47.21787264,
       51.91408083, 41.48575383, 47.13905851, 70.34692656, 93.57

In [7]:
A.shape
#array.shape可以看array的形狀

(100,)

In [10]:
A.shape=(5, 20)
#五個元素，一個元素有二十個數

In [11]:
Ａ

array([[-6.07981329e-01,  5.06788325e-02,  2.26640465e-01,
        -1.36278751e-01,  1.72457716e+00, -3.31034898e-01,
        -1.79409284e+00,  5.28257295e-01, -2.90338751e-01,
        -7.27570282e-01,  9.96748604e-01,  1.94089322e-01,
         7.76232994e-01,  9.44647312e-01,  4.83919332e-01,
         2.41689769e+00, -3.72473621e-01, -1.61176632e-01,
         4.43376112e-01, -4.33833769e-01],
       [ 7.90817054e-01,  1.58497859e+00,  7.60027401e-01,
        -1.42730570e+00, -7.12569631e-01,  5.43512898e-02,
        -4.11466221e-01, -8.19671415e-01, -4.53203550e-01,
         2.55645074e-01, -8.42220424e-01,  1.17009473e+00,
         2.05905759e-01, -1.17627675e-01,  8.31510307e-01,
         1.49828798e-01, -1.50781748e+00, -9.13922465e-01,
         5.30718880e-01, -1.25482642e+00],
       [-1.75204014e-01,  2.78228428e-01, -2.97679890e-01,
        -2.74968146e-01, -9.78558410e-02,  1.45284261e+00,
        -7.54687155e-01,  1.13225759e+00,  9.51606002e-01,
        -9.96832001e-01, -1.1

In [12]:
A.reshape(100,1)
#產生一個新的array，不會改原本的

array([[-6.07981329e-01],
       [ 5.06788325e-02],
       [ 2.26640465e-01],
       [-1.36278751e-01],
       [ 1.72457716e+00],
       [-3.31034898e-01],
       [-1.79409284e+00],
       [ 5.28257295e-01],
       [-2.90338751e-01],
       [-7.27570282e-01],
       [ 9.96748604e-01],
       [ 1.94089322e-01],
       [ 7.76232994e-01],
       [ 9.44647312e-01],
       [ 4.83919332e-01],
       [ 2.41689769e+00],
       [-3.72473621e-01],
       [-1.61176632e-01],
       [ 4.43376112e-01],
       [-4.33833769e-01],
       [ 7.90817054e-01],
       [ 1.58497859e+00],
       [ 7.60027401e-01],
       [-1.42730570e+00],
       [-7.12569631e-01],
       [ 5.43512898e-02],
       [-4.11466221e-01],
       [-8.19671415e-01],
       [-4.53203550e-01],
       [ 2.55645074e-01],
       [-8.42220424e-01],
       [ 1.17009473e+00],
       [ 2.05905759e-01],
       [-1.17627675e-01],
       [ 8.31510307e-01],
       [ 1.49828798e-01],
       [-1.50781748e+00],
       [-9.13922465e-01],
       [ 5.3

In [13]:
A = A.reshape(100, 1)

In [14]:
A

array([[-6.07981329e-01],
       [ 5.06788325e-02],
       [ 2.26640465e-01],
       [-1.36278751e-01],
       [ 1.72457716e+00],
       [-3.31034898e-01],
       [-1.79409284e+00],
       [ 5.28257295e-01],
       [-2.90338751e-01],
       [-7.27570282e-01],
       [ 9.96748604e-01],
       [ 1.94089322e-01],
       [ 7.76232994e-01],
       [ 9.44647312e-01],
       [ 4.83919332e-01],
       [ 2.41689769e+00],
       [-3.72473621e-01],
       [-1.61176632e-01],
       [ 4.43376112e-01],
       [-4.33833769e-01],
       [ 7.90817054e-01],
       [ 1.58497859e+00],
       [ 7.60027401e-01],
       [-1.42730570e+00],
       [-7.12569631e-01],
       [ 5.43512898e-02],
       [-4.11466221e-01],
       [-8.19671415e-01],
       [-4.53203550e-01],
       [ 2.55645074e-01],
       [-8.42220424e-01],
       [ 1.17009473e+00],
       [ 2.05905759e-01],
       [-1.17627675e-01],
       [ 8.31510307e-01],
       [ 1.49828798e-01],
       [-1.50781748e+00],
       [-9.13922465e-01],
       [ 5.3