In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
grades = np.array([[85, 70, 92], [75, 88, 91], [84, 98, 93], [77, 84, 82]])

In [3]:
grades

array([[85, 70, 92],
       [75, 88, 91],
       [84, 98, 93],
       [77, 84, 82]])

In [4]:
weights= np.array([0.3, 0.4, 0.3])

In [5]:
np.dot(grades, weights)

array([81.1, 85. , 92.3, 81.3])

In [6]:
L = np.array([3, 5, 7, 9])

In [7]:
L*3

array([ 9, 15, 21, 27])